name: 'Github Action Log Cleaner'
author: 'Jose Miguel Miranda'
description: 'Limpia los logs/ejecuciones generados por Github Actions en un repo'

inputs:
  owner:
    description: "Owner del repo que queremos limpiar"
    required: true

  repo:
    description: "Nombre del Repo que queremos limpilar"
    required: true

  num_runs:
    description: "Numero Logs/Ejeuciones que dejamos sin borrar"
    required: false
    default: 10

  myToken:
    description: "PAT con permiso escritura en el repo"
    required: true
      

outputs:
  output_text:
    description: 'Temporal'
  
runs:
  using: 'node12'
  main: 'src/main.js'

branding:
  icon: 'delete'
  color: 'yellow'
